config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
      !!current_user
    end

    def require_user
      if !logged_in?
        flash[:alert] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
  
    # GET /articles or /articles.json
    def index
      @articles = Article.paginate(page: params[:page], per_page: 5)
    end
  
    # GET /articles/1 or /articles/1.json
    def show
      
    end
  
    # GET /articles/new
    def new
      @article = Article.new
    end
  
    # GET /articles/1/edit
    def edit
    end
  
    # POST /articles or /articles.json
    def create
      
      @article = Article.new(article_params)
      @article.user = current_user
      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: "Article was successfully created." }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /articles/1 or /articles/1.json
    def update
      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: "Article was successfully updated." }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /articles/1 or /articles/1.json
    def destroy
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_path, notice: "Article was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      
      def set_article
        @article = Article.find(params[:id])
      end
      # Only allow a list of trusted parameters through.
      def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
      end
  
      def require_same_user
        if current_user != @article.user && !current_user.admin?
          flash[:alert] = "You can only edit or delete your own article"
          redirect_to @article
        end
      end
  
      
  end
  

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    def new
        @category = Category.new
    end
    def create
        @category = Category.new(category_params)

        respond_to do |format|
            if @category.save
              format.html { redirect_to @category, notice: "Category was successfully created" }
              format.json { render :show, status: :created, location: @category }
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @category.errors, status: :unprocessable_entity }
            end
        end

    end
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private 

    def category_params 
        params.require(:category).permit(:name)
    end
    def require_admin
        if !(logged_in? && current_user.admin?)
          flash[:alert] = "Only admins can perform that action"
          redirect_to categories_path
        end
    end
    def edit
        @category = Category.find(params: [:id]) 
    end

    def update
        @category = Category.find(params: [:id]) 
        if @category.update(category_params)
            flash[:notice] = "Category name updeted successfully"
            redirect_to @category
        else
            render 'edit'
        end



    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      render file: '.pages/home.html.erb'
       redirect_to articles_path if logged_in? 
     end
     
    def about
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "Logged in successfully"
        redirect_to user
      else
        flash.now[:alert] = "There was something wrong with your login details"
        render 'new'
      end
    end
  
    def destroy
      session[:user_id] = nil
      flash[:notice] = "Logged out"
      redirect_to root_path
    end
  
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]
  
    def show
      @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end
  
    def index
      @users = User.paginate(page: params[:page], per_page: 5)
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def update
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        redirect_to @user
      else
        render 'edit'
      end
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
        redirect_to articles_path
      else
        render 'new'
      end
    end
  
    def destroy
      @user.destroy
      session[:user_id] = nil if @user == current_user
      flash[:notice] = "Account and all associated articles successfully deleted"
      redirect_to articles_path
    end
  
    private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
  
    def set_user
      @user = User.find(params[:id])
    end
  
    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own account"
        redirect_to @user
      end
    end
    
  end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}" 
      
        image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

   

    
    
     
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="container ">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class=" mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic cimg">
            <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user)  %>
            <% end%>
            <% if article.categories.any? %>
              <div class="mt-2"><%= render article.categories %> </div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?)  %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted cimg">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div> 

app/views/articles/show.html.erb
  <h2 class="text-center mt-4"><%= @article.title %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class=" mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header cimg font-italic">
            by <%= @article.user.username if @article.user %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
            <% if @article.categories.any? %>
              <div class="mt-2"><%= render @article.categories %> </div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted cimg">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
        
      </div>
       
    </div>
  </div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to ' Cancel and return to category ', category_path(@category), class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category:<%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

 <div class="flickr_pagination">                        
   <%= will_paginate @articles, :container => false %>   
 </div>  

  <%= render 'articles/article' %>

 <div class="flickr_pagination mb-4">               
   <%= will_paginate @articles, :container => false %>
 </div> 

app/views/layouts/_navigation.html.erb
 

<nav class="navbar navbar-expand-lg navbar-dark " >
    
  
  

  
  <div class="collapse navbar-collapse " id="navbarSupportedContent"> 
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
        
      </li>
      <li class="nav-item">
        
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View articles", articles_path, class:"dropdown-item" %>
      
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class:"dropdown-item" %>
      
          
        </div>
      </li>

        <% if logged_in? %>
         
        
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        <%= link_to gravatar_for(current_user, size: 50), current_user %>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    
  </div>
  



  
<!--        боковое меню     -->

<button class="btn navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
  <!-- <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"> -->
    <i class="fas fa-sign-out-alt btncolor"></i>
    <!-- <span class="navbar-toggler-icon"></span>  -->
  </button>
  
  

<div class="offcanvas offcanvas-start " data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header ">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo1" %>
        <% if logged_in? %>
          <%= link_to gravatar_for(current_user, size: 50), current_user %> 
        <% end%>
    <button class="btn-close btncolor navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
  <!-- <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"> -->
      <!-- <span class="navbar-toggler-icon"></span>  -->
      
    </button>
  </div>
  
  <div class="offcanvas-body ">
    
    <ul class="navbar-nav mr-auto">
      
      
      <li class="nav-item">
        
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu spisok" aria-labelledby="navbarDropdown">

          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View articles", articles_path, class:"dropdown-item nav-item" %>
      
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class:"dropdown-item" %>
          
      
          
        </div>
      </li>

        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</div>


  
</nav>

  


<div class="bt b--light-silver w-100"></div>
  <script>
    $(function() {
    
      $('#top').click(function() {
      
        $("html, body").animate({
          scrollTop:0
        },1000);
      })
    })

    $(window).scroll(function() {

      if ($(this).scrollTop()>200) {
      
        $('#top').fadeIn();
      }

      else {
        $('#top').fadeOut();
      }
    });
  </script>
  <div id="top" >  
     <i class="far fa-arrow-alt-circle-up"></i>
  </div>
  

app/views/layouts/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark " >
    
  <div class="collapse navbar-collapse " id="navbarSupportedContent"> 
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
        
      </li>
      <li class="nav-item">
        
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View articles", articles_path, class:"dropdown-item" %>
      
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class:"dropdown-item" %>
      
          
        </div>
      </li>

        <% if logged_in? %>
         
        
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        <%= link_to gravatar_for(current_user, size: 50), current_user %>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    
  </div>
  



  
<!--        боковое меню     -->

<button class="btn navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
  <!-- <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"> -->
    <i class="fas fa-sign-out-alt btncolor"></i>
    <!-- <span class="navbar-toggler-icon"></span>  -->
  </button>
  
  

<div class="offcanvas offcanvas-start " data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling" aria-labelledby="offcanvasScrollingLabel">
  <div class="offcanvas-header ">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo1" %>
        <% if logged_in? %>
          <%= link_to gravatar_for(current_user, size: 50), current_user %> 
        <% end%>
    <button class="btn-close btncolor navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling">
  <!-- <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar"> -->
      <!-- <span class="navbar-toggler-icon"></span>  -->
      
    </button>
  </div>
  
  <div class="offcanvas-body ">
    
    <ul class="navbar-nav mr-auto">
      
      
      <li class="nav-item">
        
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu spisok" aria-labelledby="navbarDropdown">

          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View articles", articles_path, class:"dropdown-item nav-item" %>
      
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class:"dropdown-item" %>
          
      
          
        </div>
      </li>

        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</div>


  
</nav>

  


<div class="bt b--light-silver w-100"></div>
  <script>
    $(function() {
    
      $('#top').click(function() {
      
        $("html, body").animate({
          scrollTop:0
        },1000);
      })
    })

    $(window).scroll(function() {

      if ($(this).scrollTop()>200) {
      
        $('#top').fadeIn();
      }

      else {
        $('#top').fadeOut();
      }
    });
  </script>
  <div id="top" >  
     <i class="far fa-arrow-alt-circle-up"></i>
  </div>
  

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-md-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic cimg">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted cimg">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>